const express = require('express');
const cors = require('cors');
const { errorHandler } = require('./middleware/errorMiddleware');
const app = express();
app.use(cors({ origin: process.env.CLIENT_ORIGIN || 'http://localhost:8080' }));
app.use(express.json({ limit: '100kb' }));
app.use(express.urlencoded({ extended: false }));
for (const name of ['auth', 'chat', 'profile', 'diet', 'dashboard', 'vision', 'exercises', 'workouts']) app.use('/api/' + name, require('./routes/' + name));
app.get('/', (req, res) => res.json({ status: 'ok' }));
app.use((req, res) => res.status(404).json({ error: 'Endpoint not found' }));
app.use(errorHandler);
module.exports = app;
